name: Upload JavaScript Sourcemaps to Datadog
description: Upload JavaScript Sourcemaps to Datadog
branding:
  icon: hard-drive
  color: blue
inputs:
  api-key:
    description: DataDog API Key
    required: true
  path:
    description: Path of JavaScript Sourcemaps files
    required: true
  service:
    description: Service Name
    required: true      
  minified-path-prefix:
    description: Minified Path Prefix
    required: true    
  release-version:
    description: Release Version (Usually Github Head Commit SHA)
runs:
  using: "composite"
  steps:
    - name: Set Node.js
      uses: actions/setup-node@v3

    - name: Install DataDog CI
      shell: bash
      run: npm install -g @datadog/datadog-ci

    - name: Upload Sourcemaps
      shell: bash
      env:
        DATADOG_API_KEY: ${{ inputs.api-key }}
      run: |
        datadog-ci sourcemaps upload ${{ inputs.path }} \
        --service=${{ inputs.service }} \
        --minified-path-prefix=${{ inputs.minified-path-prefix }}
      # --release-version=${{ inputs.release-version }} \
        
